name: Create diagram
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "images/diagram.svg"
          excluded_paths: ".github,__pycache__,venv,.idea"
